// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAID2E2OplCZmn7GT3eD0csVdDy3c9286I',
    appId: '1:889706880088:web:a73ba81fcd35dde9a43e2d',
    messagingSenderId: '889706880088',
    projectId: 'quicksplit-f7771',
    authDomain: 'quicksplit-f7771.firebaseapp.com',
    storageBucket: 'quicksplit-f7771.firebasestorage.app',
    measurementId: 'G-XFWM4ZBEYP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnpoyhiSgY8rL-RuMS2BzaZprzmKT6woQ',
    appId: '1:889706880088:android:dccc5942d15240dca43e2d',
    messagingSenderId: '889706880088',
    projectId: 'quicksplit-f7771',
    storageBucket: 'quicksplit-f7771.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRf4ALWTwWw8Aj1ny_rXXsdLav75hd8Us',
    appId: '1:889706880088:ios:a5afd77a8fa99839a43e2d',
    messagingSenderId: '889706880088',
    projectId: 'quicksplit-f7771',
    storageBucket: 'quicksplit-f7771.firebasestorage.app',
    iosBundleId: 'com.janakiram.quicksplit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRf4ALWTwWw8Aj1ny_rXXsdLav75hd8Us',
    appId: '1:889706880088:ios:2cf59a2d53d59c8fa43e2d',
    messagingSenderId: '889706880088',
    projectId: 'quicksplit-f7771',
    storageBucket: 'quicksplit-f7771.firebasestorage.app',
    iosBundleId: 'com.example.quicksplit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAID2E2OplCZmn7GT3eD0csVdDy3c9286I',
    appId: '1:889706880088:web:c2fb91564b7d2e25a43e2d',
    messagingSenderId: '889706880088',
    projectId: 'quicksplit-f7771',
    authDomain: 'quicksplit-f7771.firebaseapp.com',
    storageBucket: 'quicksplit-f7771.firebasestorage.app',
    measurementId: 'G-YFLNBVRGMM',
  );
}
